- name: Install ntp if not there
  package: name=ntp state=present
  become: yes

- name : Comment old ntp servers
  replace: dest="{{ ntp_conf_file }}" regexp='^(server \d+.*)$' replace='#\1' backup=yes
  become: yes

- name: install package
  lineinfile: "dest={{ ntp_conf_file }} line='{{ item }}' state=present"
  with_items: "{{ ntp_servers }}"
  become: yes

- name: restart server
  service: name=ntp state=restarted
  become: yes
